DON\CloudBundle\Entity\Server:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            errorPath: name
            message: don.server.name.already

    properties:
        name:
            - NotBlank:
                message: don.server.name.blank
        size:
            - NotBlank:
                message: don.server.size.blank

        status:
            - NotBlank:
                message: don.server.status.blank

        priceCreate:
            - NotBlank:
                message: don.server.price_create.blank

        priceHourly:
            - NotBlank:
                message: don.server.price_hourly.blank

        priceMonthly:
            - NotBlank:
                message: don.server.price_monthly.blank

DON\CloudBundle\Entity\SSHKey:
    properties:
        name:
            - NotBlank:
                message: don.sshkey.name.blank

        publicKey:
            - NotBlank:
                message: don.sshkey.public_key.blank

DON\CloudBundle\Entity\Domain:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            errorPath: name
            message: don.domain.name.already

    properties:
        name:
            - NotBlank:
                message: don.domain.name.blank