<?php

namespace DON\CloudBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * DomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends EntityRepository
{
    /**
     * @param UserInterface $user
     * @return Domain[]
     */
    public function findByUser(UserInterface $user)
    {
        return $this->findBy(array('user' => $user));
    }
}
