<?php

namespace DON\CloudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServerErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerErrorRepository extends EntityRepository
{
}
