<?php

namespace DON\CloudBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * ServerRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRepository extends EntityRepository
{
    /**
     * @param $name
     * @return Server[]
     */
    public function findByName($name)
    {
        return $this->findBy(array('name' => $name));
    }

    /**
     * @param UserInterface $user
     * @return Server[]
     */
    public function findByUser(UserInterface $user)
    {
        return $this->findBy(array('user' => $user));
    }

    /**
     * @param UserInterface $user
     * @return Server[]
     */
    public function findDeletedByUser(UserInterface $user)
    {
        return $this->findBy(array('deleted' => true, 'user' => $user));
    }
}
