<?php

namespace DON\CloudBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * ServerRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRepository extends EntityRepository
{
    public function findByUser(UserInterface $user)
    {
        return $this->findBy(array('user' => $user));
    }

    public function findByName($name)
    {
        return $this->findBy(array('name' => $name));
    }

    public function findDeletedByUser(UserInterface $user)
    {
        return $this->findBy(array('deleted' => true, 'user' => $user));
    }
}
